server:
  port: 8091

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5435/SocialMediaBA
    username: postgres
    password: bbhhmm12
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      format-sql: true